# Generated by Django 3.0.2 on 2020-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='anilbhattarai@gmail.com', max_length=80),
            preserve_default=False,
        ),
    ]
