# Generated by Django 3.0.2 on 2020-01-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_on',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
