# Generated by Django 3.0.2 on 2020-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('posted_on', 'post', 'writer')},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='air-pollution-needs-urgent-action', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%M'),
        ),
    ]
