# Generated by Django 3.0.2 on 2020-01-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200123_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
