# Generated by Django 3.0.2 on 2020-01-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ('send_date', 'name')},
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(default='anilbhattarai@gmail.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='name',
            field=models.CharField(default='Anil Bhattarai', max_length=200),
            preserve_default=False,
        ),
    ]
